"use client";

import { useEffect, useState } from "react";
import type { Insight } from "@/lib/vm-analytics/types";
import type { InsightInput } from "@/lib/vm-analytics/insights";

// Renders the rule-based commentary instantly (SSR-provided `initial`), then
// asks /api/insights to upgrade it with Claude when a key is configured.
export function Commentary({
  initial,
  input,
}: {
  initial: Insight;
  input: InsightInput;
}) {
  const [insight, setInsight] = useState<Insight>(initial);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    let cancelled = false;
    // Re-scope immediately to the newly-selected store/week's SSR draft. Without
    // this, switching stores keeps showing the previously-loaded store because
    // useState ignores changes to `initial` after mount.
    setInsight(initial);
    setLoading(true);
    fetch("/api/vm-analytics/insights", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ input }),
    })
      .then((r) => r.json())
      .then((data: Insight) => {
        // Accept any valid insight — including ones with an empty summary (the
        // Executive dashboard has no summary, only bullets). Guarding on
        // `data.summary` here is what stopped store switches from updating.
        const valid =
          data && (data.summary || (Array.isArray(data.bullets) && data.bullets.length > 0));
        if (!cancelled && valid) setInsight(data);
      })
      .catch(() => {})
      .finally(() => !cancelled && setLoading(false));
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [JSON.stringify(input)]);

  const isClaude = insight.source === "claude";

  return (
    <div className="vm-card p-5">
      <div className="mb-2 flex items-center gap-2">
        <span className="text-sm font-semibold text-text-primary">
          Automated Commentary
        </span>
        <span
          className={`rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide ${
            isClaude
              ? "bg-gold/20 text-gold"
              : "bg-surface-hover text-text-muted border border-border"
          }`}
          title={
            isClaude
              ? "Generated by Claude"
              : "Rule-based (set ANTHROPIC_API_KEY for Claude-written commentary)"
          }
        >
          {isClaude ? "Claude" : "Auto"}
        </span>
        {loading && (
          <span className="text-[10px] text-text-muted">refining…</span>
        )}
      </div>
      {insight.summary && (
        <p className="text-sm leading-relaxed text-text-primary">{insight.summary}</p>
      )}
      {insight.bullets.length > 0 && (
        <ul className="mt-3 space-y-1.5">
          {insight.bullets.map((b, i) => (
            <li key={i} className="flex gap-2 text-sm text-text-muted">
              <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-gold" />
              <span>{b}</span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
