"use client";

import { useEffect, useState } from "react";
import type { Insight } from "@/lib/vm-analytics/types";
import type { InsightInput } from "@/lib/vm-analytics/insights";

// Renders the rule-based commentary instantly (SSR-provided `initial`), then
// asks /api/insights to upgrade it with Claude when a key is configured.
export function Commentary({
  initial,
  input,
}: {
  initial: Insight;
  input: InsightInput;
}) {
  const [insight, setInsight] = useState<Insight>(initial);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    fetch("/api/vm-analytics/insights", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ input }),
    })
      .then((r) => r.json())
      .then((data: Insight) => {
        if (!cancelled && data && data.summary) setInsight(data);
      })
      .catch(() => {})
      .finally(() => !cancelled && setLoading(false));
    return () => {
      cancelled = true;
    };
  }, [JSON.stringify(input)]);

  const isClaude = insight.source === "claude";

  return (
<div className="rounded-xl border border-white/10 bg-gradient-to-br from-zinc-900 via-black to-zinc-800 p-5 shadow-sm">
      <div className="mb-2 flex items-center gap-2">
        <span className="text-sm font-semibold text-brand-dark">
          Automated Commentary
        </span>
        <span
          className={`rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide ${
            isClaude
              ? "bg-white text-black"
              : "bg-slate-200 text-black"
          }`}
          title={
            isClaude
              ? "Generated by Claude"
              : "Rule-based (set ANTHROPIC_API_KEY for Claude-written commentary)"
          }
        >
          {isClaude ? "Claude" : "Auto"}
        </span>
        {loading && (
          <span className="text-[10px] text-ink-faint">refining…</span>
        )}
      </div>
      <p className="text-sm leading-relaxed text-ink">{insight.summary}</p>
      {insight.bullets.length > 0 && (
        <ul className="mt-3 space-y-1.5">
          {insight.bullets.map((b, i) => (
            <li key={i} className="flex gap-2 text-sm text-ink-soft">
              <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-brand" />
              <span>{b}</span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
