// =============================================================
// Resend email sender (server-only, dependency-free via fetch).
//
// Sends a single digest email for newly-created alerts. Best-effort by design:
// it NEVER throws and silently no-ops when email isn't configured, so an alert
// scan never fails just because email isn't set up.
//
// Configure with two server env vars:
//   RESEND_API_KEY    — your Resend API key
//   ALERT_EMAIL_FROM  — verified sender, e.g. "Peckers Alerts <alerts@yourdomain>"
// =============================================================

import type { AlertSeverity, AlertType } from "./types";

type DigestAlert = {
  title: string;
  message: string;
  severity: AlertSeverity;
  alert_type: AlertType;
};

export type EmailResult = { sent: boolean; reason?: string };

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Is email configured + ready to send? (Doesn't check the per-scan toggle.) */
export function isEmailConfigured(): boolean {
  return Boolean(process.env.RESEND_API_KEY);
}

/**
 * Send a single plain email via Resend. Best-effort — never throws; returns
 * {sent:false, reason} when not configured / no recipients / API error.
 */
export async function sendEmail(input: {
  recipients: string[];
  subject: string;
  html: string;
  text?: string;
}): Promise<EmailResult> {
  try {
    const apiKey = process.env.RESEND_API_KEY;
    const from =
      process.env.ALERT_EMAIL_FROM ||
      "Peckers Alerts <alerts@peckers-app.co.uk>";
    if (!apiKey) return { sent: false, reason: "RESEND_API_KEY not set" };
    const to = Array.from(new Set(input.recipients.filter(Boolean)));
    if (to.length === 0) return { sent: false, reason: "no recipients" };

    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from,
        to,
        subject: input.subject,
        html: input.html,
        text: input.text ?? input.subject,
      }),
    });
    if (!res.ok) {
      const body = await res.text().catch(() => "");
      return { sent: false, reason: `Resend ${res.status}: ${body.slice(0, 200)}` };
    }
    return { sent: true };
  } catch (err) {
    return { sent: false, reason: err instanceof Error ? err.message : "email error" };
  }
}

/**
 * Send one digest email summarising new alerts. Returns {sent:false, reason}
 * (never throws) when not configured, no recipients, or the API rejects it.
 */
export async function sendAlertDigest(input: {
  recipients: string[];
  alerts: DigestAlert[];
}): Promise<EmailResult> {
  try {
    const apiKey = process.env.RESEND_API_KEY;
    const from =
      process.env.ALERT_EMAIL_FROM ||
      "Peckers Alerts <alerts@peckers-app.co.uk>";
    if (!apiKey) return { sent: false, reason: "RESEND_API_KEY not set" };

    const to = Array.from(new Set(input.recipients.filter(Boolean)));
    if (to.length === 0) return { sent: false, reason: "no recipients" };
    if (input.alerts.length === 0) return { sent: false, reason: "no alerts" };

    const count = input.alerts.length;
    const subject = `Peckers: ${count} new alert${count === 1 ? "" : "s"}`;
    const rows = input.alerts
      .map(
        (a) =>
          `<tr><td style="padding:10px 12px;border-bottom:1px solid #eee;">` +
          `<strong>${escapeHtml(a.title)}</strong><br>` +
          `<span style="color:#555;font-size:13px;">${escapeHtml(a.message)}</span>` +
          `</td></tr>`,
      )
      .join("");
    const html =
      `<div style="font-family:Arial,Helvetica,sans-serif;max-width:560px;margin:0 auto;">` +
      `<h2 style="margin:0 0 4px;">Peckers — ${count} new alert${count === 1 ? "" : "s"}</h2>` +
      `<p style="color:#666;margin:0 0 12px;font-size:14px;">Generated by the rota system. Sign in to review and resolve.</p>` +
      `<table style="width:100%;border-collapse:collapse;border:1px solid #eee;">${rows}</table>` +
      `</div>`;
    const text = input.alerts
      .map((a) => `• ${a.title}\n  ${a.message}`)
      .join("\n\n");

    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ from, to, subject, html, text }),
    });

    if (!res.ok) {
      const body = await res.text().catch(() => "");
      return { sent: false, reason: `Resend ${res.status}: ${body.slice(0, 200)}` };
    }
    return { sent: true };
  } catch (err) {
    return {
      sent: false,
      reason: err instanceof Error ? err.message : "email error",
    };
  }
}
